# Generated by Django 4.1.5 on 2023-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
